### ISSUE TITLE
testdevice model plugin cannot be initialized 

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/config-models#60]
I was doing some tests and I noticed testdevice-2.0.0 model cannot be initialized. Something to investigate later. 

```
panic: schema error: could not unzip the schema; json: cannot unmarshal object into Go struct field ListAttr.Dir.Dir.ListAttr.MaxElements of type uint64

goroutine 1 [running]:
github.com/onosproject/config-models/modelplugin/testdevice-2.0.0/testdevice_2_0_0.init.0()
```

**Comment by adibrastegarnia** [comment]
@SeanCondon 
I see this even on generating simple models (e.g for ric). It seems the go.mod deps all are identical like aether and rbac model plugins. Is it possible you generate the model plugin for ric  example with your ygot and see you can initialize it like this. Perhaps something is off in my environment. 

```
v1Models := NewModel(ricmodelplugin.ModelData,
		reflect.TypeOf((*ricmodelv1.Device)(nil)),
		ricmodelv1.SchemaTree["Device"],
		ricmodelv1.Unmarshal,
		map[string]map[int64]ygot.EnumDefinition{},
	)
```

**Comment by adibrastegarnia** [comment]
@SeanCondon 
That code above works with other model plugins like aether

**Comment by SeanCondon** [comment]
@adibrastegarnia When you say "testdevice-2.0.0 model cannot be initialized" - i'm not clear what you mean . Do you mean when it's loaded in to `onos-config` at startup or something?

**Comment by adibrastegarnia** [comment]
@SeanCondon 
Not loading part. In the target side like what we do in the simulator or sdcore-adapter like this

**Comment by adibrastegarnia** [comment]
Or this one 
https://github.com/onosproject/sdcore-adapter/blob/c49f388f4c338d02535fd71071c2130f4682110b/cmd/sdcore-migrate/sdcore-migrate.go#L51

**Comment by sbconsulting** [comment]
In sdcore-adapter, I recently moved the modeldata into a library inside of config_models (see recent patch there) to make it easy to import.

**Comment by adibrastegarnia** [comment]
@sbconsulting 
Yep I did the same thing that as you did and it is really good idea to avoid hard coding it in the agent. The problem in my case is that I can use your model plugin to initialize things without any error but for a simple model (like what we have in testdevice), I am getting the above error when I call NewModel

**Comment by teone** [comment]
@adibrastegarnia does this still applies or can we close it?

**Comment by adibrastegarnia** [comment]
> @adibrastegarnia does this still applies or can we close it?

Closed. Thanks for checking
